### ISSUE TITLE
This repository does not work with Joomla patchtester

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-extensions/weblinks#202]
This repository does not work with Joomla Patchtester.

Joomla (https://github.com/joomla/joomla-cms) and patchtester (https://github.com/joomla-extensions/patchtester).

![image](https://cloud.githubusercontent.com/assets/9630530/13881260/17ff7176-ed18-11e5-9428-44aa61c0fa19.png)

The PR are fetched but cannot be applied.

I think the structure of the folders needs to be like the patchtester repository.

**Comment by mbabker** [comment]
Repos have to match the structure of the main CMS to work with the patchtester component.  There's no compulsory mandate that all repos have to be structured that way.  Actually the reason the patchtester does is because that's the structure it was in when I inherited it, https://github.com/BabDev/Podcast-Manager is my preferred repo structure but you know what they say about opinions :wink:

**Comment by andrepereiradasilva** [comment]
@mbabker and is it possible for the patchtester to have a setting to define something like a home path (within the repository)?

For instance:

For weblinks (Repository: /src/[joomla normal paths])
Repository home path: /src/

For joomla, patchtester, com_localise (Repository: /[joomla normal paths])
Repository home path: / (default)

That way it will also work in weblinks (i think).

**Comment by mbabker** [comment]
No.  Because that still assumes that the directory structure matches the Joomla core from that point forward (which it does with the case of weblinks, com_localise doesn't (the master branch does but that hasn't been touched in almost 2 years, the active develop branch doesn't)).

For an extension to work correctly with the patchtester, it MUST use the same repo structure.  Not doing so introduces the need for either config parameters that aren't reliable (now the patch processor has to figure out the extra path handling) or the component has to have per-repository configurations hardcoded into it.

**Comment by andrepereiradasilva** [comment]
ok i understand, so it's up to repositories maintainers to do that structure change right?

**Comment by mbabker** [comment]
Yep.  And considering the automated test group has restructured at least two repos to match their packaging tools, I doubt they're going to do it yet again for this.

**Comment by chrisdavenport** [comment]
Closing as there doesn't appear to be a reasonable solution.
