### ISSUE TITLE
Submit Web Link menu item with Access Guest or Public results in requested page can't be found

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla-extensions/weblinks#276]
#### Steps to reproduce the issue
Add a menu item "Submit a Web Link" (official WebLinks component).
Keep the Access of the menu item "Public".
Go to the fronend (no login).

#### Expected result
The possibility to add a weblink for everybody on the site.

#### Actual result
Message: "The requested page can't be found."

#### System information (as much as possible)
Clean install J 3.6.4.

#### Additional comments
Turning the Access of the menu item into "Registered" makes the menu item vissible or the message "Please login first."

**Comment by zero-24** [comment]
Hi @MartijnMaandag 

I can't confirm this issue. On a default 3.7.0b2 + the lastest weblinks package. i get a `403 Error`

![image](https://cloud.githubusercontent.com/assets/2596554/22967704/e39ce448-f367-11e6-8ca8-dd2b580ace6f.png)

And this is correct as the public group is not allowed to create weblinks:
![image](https://cloud.githubusercontent.com/assets/2596554/22967751/06c433b8-f368-11e6-88b6-a8da3548f5e8.png)

If i allow them to create weblinks it work without error message because they are allowed to create things.

Can you confirm that as expected behavior?

**Comment by yvesh** [comment]
> The possibility to add a weblink for everybody on the site.

In terms of security it's a real bad idea having that form public!

**Comment by MartijnMaandag** [comment]
Yes you are right, did not look far enough.
I will close the issue.
