### ISSUE TITLE
Index Weblink Description + Extra Fields in Title Filter

### ISSUE THREAD

**Issue by modusworks** [joomla-extensions/weblinks#481]
Could we consider adding an option to index weblink descriptions (most important) and secondarily any extra field information if present. Regarding extra fields I suspect all could be accomplished with text fields and text area. 

For large catalogs of weblinks, the title filter search is a bit limited for generating ideal results. Expanding the index of the title filter seems like the ideal option to keep results segregated from com_content and others.

Thanks Team!

**Comment by joomdonation** [comment]
I guess you are talking about indexing in smart search component? As of right now, I don't have a good knowledge about how smart search component really works, so I could not answer this question. Maybe someone has better understand how smart search works could help

**Comment by modusworks** [comment]
Well, I was referencing Weblinks built-in search/fitler function. Currently, it only will look for information in a weblink title. It does not index/search/ provide results for any information contained within a weblink description or extra fields.

**Comment by rogercreagh** [comment]
It would be fairly easy to add an additional field to the defaul.xml for the categories view to specify search in title only (default), description only, or both.

Its then a question of reading the parameter value from the state in the model getListQuery() and adjusting the title search where clause as appropriate.

**Comment by joomdonation** [comment]
I just checked all other Joomla core components : com_content, com_contact, com_newsfeed and found that for these components, we only support basic search (base on title, name). Searching for text, description is not supported (I don't know why, could be because performance reason or searching on long text could give less accurate result).

For that reason, I won't support for this feature for now. If you need better search, use smart search component instead. It allow searching base on indexed data from title, description, and other weblinks data. For custom fields, it is not supported yet, but it will likely be supported in Joomla 4.3

If you still need this feature, you can customize the code of Category model yourself components/com_weblinks/src/Model/CategoryModel.php . Should be easy.
