### ISSUE TITLE
[3.10] Menu item type COM_WEBLINKS_WEBLINK_VIEW_DEFAULT_TITLE

### ISSUE THREAD

**Issue by Franzwohlkoenig** [joomla-extensions/weblinks#485]
### Steps to reproduce the issue
Open menu item type "Web Links" user get:

<img width="695" alt="Untitled" src="https://user-images.githubusercontent.com/89642616/155738906-ef994cca-ff59-4ee8-98d8-1a075e16006f.png">

### Expected result

Available menu item types are shown.

### Actual result

Not available menu item types ist shown.

### System information (as much as possible)

<img width="795" alt="Untitled 2" src="https://user-images.githubusercontent.com/89642616/155739328-15543e27-eb2b-400e-8dea-2857e80a7044.png">

### Additional comments

--

**Comment by rogercreagh** [comment]
This is slightly deeper than just the language string missing. As well as the label and description if you try and create a menu item of type weblink instead of a drop down box to select the weblink for the view to display you get a simple text box.

If you enter a valid id of a weblink and save it then the menu item works, anything else and it causes an error.

The problem is that the file `views\weblink\tmpl\default.xml` is referencing a custom filed type that doesn't exist

```
    	<fields name="request">
		<fieldset
			name="request"
			addfieldpath="/administrator/components/com_weblinks/models/fields"
		>

			<field name="id"
				type="modal_weblink"
				label="COM_WEBLINKS_FIELD_SELECT_WEBLINK_LABEL"
 
```
The folder /administrator/components/com_weblinks/models/fields does not exist.

It needs to contain a field type  (probably called "weblink" rather than "modal_weblink" as there is nothing modal about it) which provides a drop down list of published weblinks - fairly straightforward to create if it doesn't exist. I'll do it when I've finished my current project if no-one else gets there first (a few weeks)

In the meantime simply entering a valid weblink id in the menu form is a workaround.

**Comment by chmst** [comment]
Confirmed.

**Comment by rogercreagh** [comment]
This is slightly deeper than just the language string missing. As well as the label and description if you try and create a menu item of type weblink instead of a drop down box to select the weblink for the view to display you get a simple text box.

If you enter a valid id of a weblink and save it then the menu item works, anything else and it causes an error.

The problem is that the file views\weblink\tmpl\default.xml is referencing a custom filed type that doesn't exist

    	<fields name="request">
		<fieldset
			name="request"
			addfieldpath="/administrator/components/com_weblinks/models/fields"
		>

			<field name="id"
				type="modal_weblink"
				label="COM_WEBLINKS_FIELD_SELECT_WEBLINK_LABEL"
 
The folder /administrator/components/com_weblinks/models/fields does not exist in the installation for weblinks version 3.9 on Joomla 3.10 although it does exist in the zip file - very strange.

I notice that none of the folders in the installation include the empty index.html file which I understood was required - at least for an empty folder to be installed. 

In the github source there is a sub_folder .../models/fields/modal containing the required file weblink.php but this is not getting included in the package (and I'm not sure that the addfield path looks in subfolders?). The language strings around this have also gone AWOL.

I notice that none of the folders in the installation include the empty index.html file which I understood was required - at least for an empty folder to be installed. 

Since this is all tied up with the whole process of testing and creation of the package on here which I have no idea how it works it is beyond my pay grade to fix.

In the meantime simply entering a valid weblink id in the menu form is a workaround. Or if you are happy implementing it locally just copying the weblink.php file into the relevant folder on your site should work (albeit without language strings)

**Comment by rogercreagh** [comment]
I can confirm that the problem is that the directory `administrator/components/com_weblinks/models/fields` contains only a subdirectory `modal` and no file and so is ignored on installation.

Adding an empty `index.html` to the folder allows the installation to proceed normally and the field file can then be found.

**Comment by rogercreagh** [comment]
Regarding the missing language strings I can confirm that the following are indeed missing
```
COM_WEBLINKS_WEBLINK_VIEW_DEFAULT_OPTION="***NOT SURE WHERE THIS GETS USED***"
COM_WEBLINKS_FIELD_SELECT_WEBLINK_LABEL="Select Weblink"
COM_WEBLINKS_FIELD_SELECT_WEBLINK_DESC="Select weblink to be displayed
```
and should have appropriate values and be added to the adminstrator language file  (my suggestions for English values above)
The other two are found in the sys.ini admin language file

(it looks like this xml file gets missed by JED checker which doesn't pick up the missing strings (although it does pick up quite a lot of other stuff that should be tidied up)

**Comment by Franzwohlkoenig** [comment]
Closing as J3 now only get security updates.
