### ISSUE TITLE
Web Links shows 'Undefined variable $userId' above every link

### ISSUE THREAD

**Issue by jrmain** [joomla-extensions/weblinks#545]
### Steps to reproduce the issue

1. Upgrade Joomla site with Web Links from 3.x to 4.4.0.
2. Navigate to Web Links on web site.
3. Select a category to list links in that category.

### Expected result

1. Links are listed, with their descriptions, and work.
2. No errors or warnings are displayed.

### Actual result

1. Links are listed, with their descriptions, and work.
2. However, above every link I see this:

```
Warning: Undefined variable $userId in
/var/www/sitepath/components/com_weblinks/tmpl/category/default_items.php
on line 87
```

### System information (as much as possible)

Ubuntu Linux 18.04.6
Apache
PHP 8.0.29

### Additional comments

Web Links were working fine on the Joomla 3. site.

**Comment by alikon** [comment]
what weblink version ? it should be the lateset one 4.3.1

**Comment by jrmain** [comment]
Yes, it's 4.3.1. There's a Site package, a Site module, an Admin component, and three search-related Site plugins.

**Comment by joomdonation** [comment]
This should be fixed by this commit https://github.com/joomla-extensions/weblinks/commit/6749120fbff34cd9b6899fc5c63b4aaa38815806 and will be included in next release. For the time being, you can install this updated package of Weblinks to your site and the issue will be sorted.

[pkg-weblinks-4.3.1.zip](https://github.com/joomla-extensions/weblinks/files/13483153/pkg-weblinks-4.3.1.zip)

**Comment by jrmain** [comment]
Installed the package provided, and that fixed the problem. Thanks!

**Comment by joomdonation** [comment]
Thanks for confirming @jrmain. I'm closing this issue.
